/*
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST0                           ', N'Pos layanan 1', N'A ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST1                           ', N'Pos layanan 2', N'B ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST2                           ', N'Pos layanan 3', N'C ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST3                           ', N'Pos layanan 4', N'D ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST4                           ', N'Pos layanan 5', N'BK')
*/
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST5                           ', N'Pos Layanan 6', N'F ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST6                           ', N'Pos Layanan 7', N'G ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST7                           ', N'Pos Layanan 8', N'H ')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST8                           ', N'Pos Layanan 9', N'SA')
INSERT [dbo].[posts] ([name], [keterangan], [numberprefix]) VALUES (N'POST9                           ', N'Pos Layanan 10', N'J ')

/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'ADMIN#1                         ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'ADMIN#1                         ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'ADMIN#1                         ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'ADMIN#1                         ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'ADMIN#1                         ', N'POST4                           ', NULL, 1)
*/
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#1                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#2                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#3                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#4                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'CALL#5                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#1                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST0                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST1                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST2                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST3                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST4                           ', N'', 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'DISP#2                          ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#1                        ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST0                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST1                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST2                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST3                           ', NULL, 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST4                           ', NULL, 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#2                        ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST0                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST1                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST2                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST3                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST4                           ', N'', 1)
*/

INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#3                        ', N'POST9                           ', N'', 1)
/*
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST0                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST1                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST2                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST3                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST4                           ', N'', 1)
*/
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST5                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST6                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST7                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST8                           ', N'', 1)
INSERT [dbo].[stations] ([name], [post], [keterangan], [canlogin]) VALUES (N'TICKET#4                        ', N'POST9                           ', N'', 1)
