//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QueueServerHost {
            get {
                return ((string)(this["QueueServerHost"]));
            }
            set {
                this["QueueServerHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2345")]
        public int QueueServerPort {
            get {
                return ((int)(this["QueueServerPort"]));
            }
            set {
                this["QueueServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string StationPost {
            get {
                return ((string)(this["StationPost"]));
            }
            set {
                this["StationPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TICKET#1")]
        public string StationName {
            get {
                return ((string)(this["StationName"]));
            }
            set {
                this["StationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrintTicket {
            get {
                return ((bool)(this["PrintTicket"]));
            }
            set {
                this["PrintTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik - Penyerahan Resep")]
        public string Post0Caption {
            get {
                return ((string)(this["Post0Caption"]));
            }
            set {
                this["Post0Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string Post0Post {
            get {
                return ((string)(this["Post0Post"]));
            }
            set {
                this["Post0Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0Name {
            get {
                return ((string)(this["Post0Name"]));
            }
            set {
                this["Post0Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0Enabled {
            get {
                return ((bool)(this["Post0Enabled"]));
            }
            set {
                this["Post0Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Daftar Laboratorium")]
        public string Post1Caption {
            get {
                return ((string)(this["Post1Caption"]));
            }
            set {
                this["Post1Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST1")]
        public string Post1Post {
            get {
                return ((string)(this["Post1Post"]));
            }
            set {
                this["Post1Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1Name {
            get {
                return ((string)(this["Post1Name"]));
            }
            set {
                this["Post1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1Enabled {
            get {
                return ((bool)(this["Post1Enabled"]));
            }
            set {
                this["Post1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran Rawat Jalan")]
        public string Post2Caption {
            get {
                return ((string)(this["Post2Caption"]));
            }
            set {
                this["Post2Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST2")]
        public string Post2Post {
            get {
                return ((string)(this["Post2Post"]));
            }
            set {
                this["Post2Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran")]
        public string Post2Name {
            get {
                return ((string)(this["Post2Name"]));
            }
            set {
                this["Post2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2Enabled {
            get {
                return ((bool)(this["Post2Enabled"]));
            }
            set {
                this["Post2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS Kesehatan")]
        public string Post3Caption {
            get {
                return ((string)(this["Post3Caption"]));
            }
            set {
                this["Post3Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST3")]
        public string Post3Post {
            get {
                return ((string)(this["Post3Post"]));
            }
            set {
                this["Post3Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS Kesehatan")]
        public string Post3Name {
            get {
                return ((string)(this["Post3Name"]));
            }
            set {
                this["Post3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3Enabled {
            get {
                return ((bool)(this["Post3Enabled"]));
            }
            set {
                this["Post3Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3Visible {
            get {
                return ((bool)(this["Post3Visible"]));
            }
            set {
                this["Post3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartDisplayFullScreen {
            get {
                return ((bool)(this["StartDisplayFullScreen"]));
            }
            set {
                this["StartDisplayFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tobasaqueue")]
        public string QueueUserName {
            get {
                return ((string)(this["QueueUserName"]));
            }
            set {
                this["QueueUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e4ee0e54215f5e3dd7683923abe1dac8")]
        public string QueuePassword {
            get {
                return ((string)(this["QueuePassword"]));
            }
            set {
                this["QueuePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post0BtnImgOn {
            get {
                return ((string)(this["Post0BtnImgOn"]));
            }
            set {
                this["Post0BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post0BtnImgOff {
            get {
                return ((string)(this["Post0BtnImgOff"]));
            }
            set {
                this["Post0BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post1BtnImgOn {
            get {
                return ((string)(this["Post1BtnImgOn"]));
            }
            set {
                this["Post1BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post1BtnImgOff {
            get {
                return ((string)(this["Post1BtnImgOff"]));
            }
            set {
                this["Post1BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post2BtnImgOn {
            get {
                return ((string)(this["Post2BtnImgOn"]));
            }
            set {
                this["Post2BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post2BtnImgOff {
            get {
                return ((string)(this["Post2BtnImgOff"]));
            }
            set {
                this["Post2BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post3BtnImgOn {
            get {
                return ((string)(this["Post3BtnImgOn"]));
            }
            set {
                this["Post3BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post3BtnImgOff {
            get {
                return ((string)(this["Post3BtnImgOff"]));
            }
            set {
                this["Post3BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selamat Datang")]
        public string RunningText0 {
            get {
                return ((string)(this["RunningText0"]));
            }
            set {
                this["RunningText0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terimakasih")]
        public string RunningText1 {
            get {
                return ((string)(this["RunningText1"]));
            }
            set {
                this["RunningText1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TOBASA QUEUE")]
        public string PrintFooter {
            get {
                return ((string)(this["PrintFooter"]));
            }
            set {
                this["PrintFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post0PrintCopies {
            get {
                return ((short)(this["Post0PrintCopies"]));
            }
            set {
                this["Post0PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post1PrintCopies {
            get {
                return ((short)(this["Post1PrintCopies"]));
            }
            set {
                this["Post1PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post2PrintCopies {
            get {
                return ((short)(this["Post2PrintCopies"]));
            }
            set {
                this["Post2PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post3PrintCopies {
            get {
                return ((short)(this["Post3PrintCopies"]));
            }
            set {
                this["Post3PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4BC3A3AC2D6D367A74580388B20BC069C96B048DFEAF5CCDC0CE1E25BF23F39")]
        public string SecuritySalt {
            get {
                return ((string)(this["SecuritySalt"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4Caption {
            get {
                return ((string)(this["Post4Caption"]));
            }
            set {
                this["Post4Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST4")]
        public string Post4Post {
            get {
                return ((string)(this["Post4Post"]));
            }
            set {
                this["Post4Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4Name {
            get {
                return ((string)(this["Post4Name"]));
            }
            set {
                this["Post4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4Enabled {
            get {
                return ((bool)(this["Post4Enabled"]));
            }
            set {
                this["Post4Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4Visible {
            get {
                return ((bool)(this["Post4Visible"]));
            }
            set {
                this["Post4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post4BtnImgOn {
            get {
                return ((string)(this["Post4BtnImgOn"]));
            }
            set {
                this["Post4BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post4BtnImgOff {
            get {
                return ((string)(this["Post4BtnImgOff"]));
            }
            set {
                this["Post4BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post4PrintCopies {
            get {
                return ((short)(this["Post4PrintCopies"]));
            }
            set {
                this["Post4PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0PrintHeader {
            get {
                return ((string)(this["Post0PrintHeader"]));
            }
            set {
                this["Post0PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1PrintHeader {
            get {
                return ((string)(this["Post1PrintHeader"]));
            }
            set {
                this["Post1PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran RJ")]
        public string Post2PrintHeader {
            get {
                return ((string)(this["Post2PrintHeader"]));
            }
            set {
                this["Post2PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS Kesehatan")]
        public string Post3PrintHeader {
            get {
                return ((string)(this["Post3PrintHeader"]));
            }
            set {
                this["Post3PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4PrintHeader {
            get {
                return ((string)(this["Post4PrintHeader"]));
            }
            set {
                this["Post4PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrawLabelOnButtons {
            get {
                return ((bool)(this["DrawLabelOnButtons"]));
            }
            set {
                this["DrawLabelOnButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ButtonLabelFontSize {
            get {
                return ((int)(this["ButtonLabelFontSize"]));
            }
            set {
                this["ButtonLabelFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Middle")]
        public string MainMenuLabelAlignment {
            get {
                return ((string)(this["MainMenuLabelAlignment"]));
            }
            set {
                this["MainMenuLabelAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MainMenuLabelFontSize {
            get {
                return ((int)(this["MainMenuLabelFontSize"]));
            }
            set {
                this["MainMenuLabelFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI GIGI")]
        public string Post5Caption {
            get {
                return ((string)(this["Post5Caption"]));
            }
            set {
                this["Post5Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST5")]
        public string Post5Post {
            get {
                return ((string)(this["Post5Post"]));
            }
            set {
                this["Post5Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Gigi")]
        public string Post5Name {
            get {
                return ((string)(this["Post5Name"]));
            }
            set {
                this["Post5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post5Enabled {
            get {
                return ((bool)(this["Post5Enabled"]));
            }
            set {
                this["Post5Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post5Visible {
            get {
                return ((bool)(this["Post5Visible"]));
            }
            set {
                this["Post5Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post5BtnImgOn {
            get {
                return ((string)(this["Post5BtnImgOn"]));
            }
            set {
                this["Post5BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post5BtnImgOff {
            get {
                return ((string)(this["Post5BtnImgOff"]));
            }
            set {
                this["Post5BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post5PrintCopies {
            get {
                return ((short)(this["Post5PrintCopies"]));
            }
            set {
                this["Post5PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Gigi")]
        public string Post5PrintHeader {
            get {
                return ((string)(this["Post5PrintHeader"]));
            }
            set {
                this["Post5PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI ANAK")]
        public string Post6Caption {
            get {
                return ((string)(this["Post6Caption"]));
            }
            set {
                this["Post6Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST6")]
        public string Post6Post {
            get {
                return ((string)(this["Post6Post"]));
            }
            set {
                this["Post6Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Anak")]
        public string Post6Name {
            get {
                return ((string)(this["Post6Name"]));
            }
            set {
                this["Post6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post6Enabled {
            get {
                return ((bool)(this["Post6Enabled"]));
            }
            set {
                this["Post6Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post6Visible {
            get {
                return ((bool)(this["Post6Visible"]));
            }
            set {
                this["Post6Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post6BtnImgOn {
            get {
                return ((string)(this["Post6BtnImgOn"]));
            }
            set {
                this["Post6BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post6BtnImgOff {
            get {
                return ((string)(this["Post6BtnImgOff"]));
            }
            set {
                this["Post6BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post6PrintCopies {
            get {
                return ((short)(this["Post6PrintCopies"]));
            }
            set {
                this["Post6PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Anak")]
        public string Post6PrintHeader {
            get {
                return ((string)(this["Post6PrintHeader"]));
            }
            set {
                this["Post6PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI MATA")]
        public string Post7Caption {
            get {
                return ((string)(this["Post7Caption"]));
            }
            set {
                this["Post7Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST7")]
        public string Post7Post {
            get {
                return ((string)(this["Post7Post"]));
            }
            set {
                this["Post7Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Mata")]
        public string Post7Name {
            get {
                return ((string)(this["Post7Name"]));
            }
            set {
                this["Post7Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post7Enabled {
            get {
                return ((bool)(this["Post7Enabled"]));
            }
            set {
                this["Post7Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post7Visible {
            get {
                return ((bool)(this["Post7Visible"]));
            }
            set {
                this["Post7Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post7BtnImgOn {
            get {
                return ((string)(this["Post7BtnImgOn"]));
            }
            set {
                this["Post7BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post7BtnImgOff {
            get {
                return ((string)(this["Post7BtnImgOff"]));
            }
            set {
                this["Post7BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post7PrintCopies {
            get {
                return ((short)(this["Post7PrintCopies"]));
            }
            set {
                this["Post7PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Mata")]
        public string Post7PrintHeader {
            get {
                return ((string)(this["Post7PrintHeader"]));
            }
            set {
                this["Post7PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI KULIT")]
        public string Post8Caption {
            get {
                return ((string)(this["Post8Caption"]));
            }
            set {
                this["Post8Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST8")]
        public string Post8Post {
            get {
                return ((string)(this["Post8Post"]));
            }
            set {
                this["Post8Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Kulit")]
        public string Post8Name {
            get {
                return ((string)(this["Post8Name"]));
            }
            set {
                this["Post8Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post8Enabled {
            get {
                return ((bool)(this["Post8Enabled"]));
            }
            set {
                this["Post8Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post8Visible {
            get {
                return ((bool)(this["Post8Visible"]));
            }
            set {
                this["Post8Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post8BtnImgOn {
            get {
                return ((string)(this["Post8BtnImgOn"]));
            }
            set {
                this["Post8BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post8BtnImgOff {
            get {
                return ((string)(this["Post8BtnImgOff"]));
            }
            set {
                this["Post8BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post8PrintCopies {
            get {
                return ((short)(this["Post8PrintCopies"]));
            }
            set {
                this["Post8PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Kulit")]
        public string Post8PrintHeader {
            get {
                return ((string)(this["Post8PrintHeader"]));
            }
            set {
                this["Post8PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI THT")]
        public string Post9Caption {
            get {
                return ((string)(this["Post9Caption"]));
            }
            set {
                this["Post9Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST9")]
        public string Post9Post {
            get {
                return ((string)(this["Post9Post"]));
            }
            set {
                this["Post9Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli THT")]
        public string Post9Name {
            get {
                return ((string)(this["Post9Name"]));
            }
            set {
                this["Post9Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post9Enabled {
            get {
                return ((bool)(this["Post9Enabled"]));
            }
            set {
                this["Post9Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post9Visible {
            get {
                return ((bool)(this["Post9Visible"]));
            }
            set {
                this["Post9Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOn.png")]
        public string Post9BtnImgOn {
            get {
                return ((string)(this["Post9BtnImgOn"]));
            }
            set {
                this["Post9BtnImgOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\ButtonGreenOff.png")]
        public string Post9BtnImgOff {
            get {
                return ((string)(this["Post9BtnImgOff"]));
            }
            set {
                this["Post9BtnImgOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public short Post9PrintCopies {
            get {
                return ((short)(this["Post9PrintCopies"]));
            }
            set {
                this["Post9PrintCopies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli THT")]
        public string Post9PrintHeader {
            get {
                return ((string)(this["Post9PrintHeader"]));
            }
            set {
                this["Post9PrintHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0Visible {
            get {
                return ((bool)(this["Post0Visible"]));
            }
            set {
                this["Post0Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1Visible {
            get {
                return ((bool)(this["Post1Visible"]));
            }
            set {
                this["Post1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2Visible {
            get {
                return ((bool)(this["Post2Visible"]));
            }
            set {
                this["Post2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLeftMenu {
            get {
                return ((bool)(this["ShowLeftMenu"]));
            }
            set {
                this["ShowLeftMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRightMenu {
            get {
                return ((bool)(this["ShowRightMenu"]));
            }
            set {
                this["ShowRightMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\MainBrandingImage.png")]
        public string MainBrandingImage {
            get {
                return ((string)(this["MainBrandingImage"]));
            }
            set {
                this["MainBrandingImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMainBrandingImage {
            get {
                return ((bool)(this["UseMainBrandingImage"]));
            }
            set {
                this["UseMainBrandingImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tobasa Queue System")]
        public string MainLogoText {
            get {
                return ((string)(this["MainLogoText"]));
            }
            set {
                this["MainLogoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\MainLogo.png")]
        public string LogoImage {
            get {
                return ((string)(this["LogoImage"]));
            }
            set {
                this["LogoImage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>POST0</string>
  <string>POST1</string>
  <string>POST2</string>
  <string>POST3</string>
  <string>POST4</string>
  <string>POST5</string>
  <string>POST6</string>
  <string>POST7</string>
  <string>POST8</string>
  <string>POST9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPostList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPostList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0UseThemeButton {
            get {
                return ((bool)(this["Post0UseThemeButton"]));
            }
            set {
                this["Post0UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1UseThemeButton {
            get {
                return ((bool)(this["Post1UseThemeButton"]));
            }
            set {
                this["Post1UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2UseThemeButton {
            get {
                return ((bool)(this["Post2UseThemeButton"]));
            }
            set {
                this["Post2UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3UseThemeButton {
            get {
                return ((bool)(this["Post3UseThemeButton"]));
            }
            set {
                this["Post3UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4UseThemeButton {
            get {
                return ((bool)(this["Post4UseThemeButton"]));
            }
            set {
                this["Post4UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post5UseThemeButton {
            get {
                return ((bool)(this["Post5UseThemeButton"]));
            }
            set {
                this["Post5UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post6UseThemeButton {
            get {
                return ((bool)(this["Post6UseThemeButton"]));
            }
            set {
                this["Post6UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post7UseThemeButton {
            get {
                return ((bool)(this["Post7UseThemeButton"]));
            }
            set {
                this["Post7UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post8UseThemeButton {
            get {
                return ((bool)(this["Post8UseThemeButton"]));
            }
            set {
                this["Post8UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post9UseThemeButton {
            get {
                return ((bool)(this["Post9UseThemeButton"]));
            }
            set {
                this["Post9UseThemeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ThemeRedButtonColor {
            get {
                return ((string)(this["ThemeRedButtonColor"]));
            }
            set {
                this["ThemeRedButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string ThemeOrangeButtonColor {
            get {
                return ((string)(this["ThemeOrangeButtonColor"]));
            }
            set {
                this["ThemeOrangeButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public string ThemeDarkButtonColor {
            get {
                return ((string)(this["ThemeDarkButtonColor"]));
            }
            set {
                this["ThemeDarkButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public string ThemeGreenButtonColor {
            get {
                return ((string)(this["ThemeGreenButtonColor"]));
            }
            set {
                this["ThemeGreenButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string ThemeBlueButtonColor {
            get {
                return ((string)(this["ThemeBlueButtonColor"]));
            }
            set {
                this["ThemeBlueButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gainsboro")]
        public global::System.Drawing.Color LogoTextColor {
            get {
                return ((global::System.Drawing.Color)(this["LogoTextColor"]));
            }
            set {
                this["LogoTextColor"] = value;
            }
        }
    }
}
