//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tobasa Queue Display")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string AppVersion {
            get {
                return ((string)(this["AppVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VideoClip")]
        public string VideoSource {
            get {
                return ((string)(this["VideoSource"]));
            }
            set {
                this["VideoSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDevice {
            get {
                return ((string)(this["VideoInputDevice"]));
            }
            set {
                this["VideoInputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SVideo")]
        public string VideoInputDeviceSource {
            get {
                return ((string)(this["VideoInputDeviceSource"]));
            }
            set {
                this["VideoInputDeviceSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlayFromFolder")]
        public string VideoCLipMode {
            get {
                return ((string)(this["VideoCLipMode"]));
            }
            set {
                this["VideoCLipMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartDisplayFullScreen {
            get {
                return ((bool)(this["StartDisplayFullScreen"]));
            }
            set {
                this["StartDisplayFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDevicePath {
            get {
                return ((string)(this["VideoInputDevicePath"]));
            }
            set {
                this["VideoInputDevicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDeviceName {
            get {
                return ((string)(this["VideoInputDeviceName"]));
            }
            set {
                this["VideoInputDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QueueServerHost {
            get {
                return ((string)(this["QueueServerHost"]));
            }
            set {
                this["QueueServerHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2345")]
        public int QueueServerPort {
            get {
                return ((int)(this["QueueServerPort"]));
            }
            set {
                this["QueueServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISP#1")]
        public string StationName {
            get {
                return ((string)(this["StationName"]));
            }
            set {
                this["StationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string StationPost {
            get {
                return ((string)(this["StationPost"]));
            }
            set {
                this["StationPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\wav")]
        public string NumberAudioLocation {
            get {
                return ((string)(this["NumberAudioLocation"]));
            }
            set {
                this["NumberAudioLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string MaxQueueNumber {
            get {
                return ((string)(this["MaxQueueNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string MaxStationNumber {
            get {
                return ((string)(this["MaxStationNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int QueueAnimationTimeInSecond {
            get {
                return ((int)(this["QueueAnimationTimeInSecond"]));
            }
            set {
                this["QueueAnimationTimeInSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APOTIK")]
        public string Post0Caption {
            get {
                return ((string)(this["Post0Caption"]));
            }
            set {
                this["Post0Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string Post0Post {
            get {
                return ((string)(this["Post0Post"]));
            }
            set {
                this["Post0Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0Name {
            get {
                return ((string)(this["Post0Name"]));
            }
            set {
                this["Post0Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LABORATORIUM")]
        public string Post1Caption {
            get {
                return ((string)(this["Post1Caption"]));
            }
            set {
                this["Post1Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST1")]
        public string Post1Post {
            get {
                return ((string)(this["Post1Post"]));
            }
            set {
                this["Post1Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1Name {
            get {
                return ((string)(this["Post1Name"]));
            }
            set {
                this["Post1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PENDAFTARAN RJ")]
        public string Post2Caption {
            get {
                return ((string)(this["Post2Caption"]));
            }
            set {
                this["Post2Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST2")]
        public string Post2Post {
            get {
                return ((string)(this["Post2Post"]));
            }
            set {
                this["Post2Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran")]
        public string Post2Name {
            get {
                return ((string)(this["Post2Name"]));
            }
            set {
                this["Post2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS KESEHATAN")]
        public string Post3Caption {
            get {
                return ((string)(this["Post3Caption"]));
            }
            set {
                this["Post3Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST3")]
        public string Post3Post {
            get {
                return ((string)(this["Post3Post"]));
            }
            set {
                this["Post3Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS Kesehatan")]
        public string Post3Name {
            get {
                return ((string)(this["Post3Name"]));
            }
            set {
                this["Post3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0RunText {
            get {
                return ((string)(this["Post0RunText"]));
            }
            set {
                this["Post0RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1RunText {
            get {
                return ((string)(this["Post1RunText"]));
            }
            set {
                this["Post1RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran")]
        public string Post2RunText {
            get {
                return ((string)(this["Post2RunText"]));
            }
            set {
                this["Post2RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS")]
        public string Post3RunText {
            get {
                return ((string)(this["Post3RunText"]));
            }
            set {
                this["Post3RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NumberAnimationColor {
            get {
                return ((global::System.Drawing.Color)(this["NumberAnimationColor"]));
            }
            set {
                this["NumberAnimationColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3Visible {
            get {
                return ((bool)(this["Post3Visible"]));
            }
            set {
                this["Post3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DSEngineVolumeLevel {
            get {
                return ((int)(this["DSEngineVolumeLevel"]));
            }
            set {
                this["DSEngineVolumeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartNumberWithUnderscore {
            get {
                return ((bool)(this["StartNumberWithUnderscore"]));
            }
            set {
                this["StartNumberWithUnderscore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\movie")]
        public string VideoClipLocation {
            get {
                return ((string)(this["VideoClipLocation"]));
            }
            set {
                this["VideoClipLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayVideoAtStartup {
            get {
                return ((bool)(this["PlayVideoAtStartup"]));
            }
            set {
                this["PlayVideoAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReceiveMessageFromOtherPost {
            get {
                return ((bool)(this["ReceiveMessageFromOtherPost"]));
            }
            set {
                this["ReceiveMessageFromOtherPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tobasaqueue")]
        public string QueueUserName {
            get {
                return ((string)(this["QueueUserName"]));
            }
            set {
                this["QueueUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e4ee0e54215f5e3dd7683923abe1dac8")]
        public string QueuePassword {
            get {
                return ((string)(this["QueuePassword"]));
            }
            set {
                this["QueuePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>POST0</string>
  <string>POST1</string>
  <string>POST2</string>
  <string>POST3</string>
  <string>POST4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPostList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPostList"]));
            }
            set {
                this["UIPostList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selamat Datang")]
        public string RunningText0 {
            get {
                return ((string)(this["RunningText0"]));
            }
            set {
                this["RunningText0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terimakasih")]
        public string RunningText1 {
            get {
                return ((string)(this["RunningText1"]));
            }
            set {
                this["RunningText1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0PlayAudio {
            get {
                return ((bool)(this["Post0PlayAudio"]));
            }
            set {
                this["Post0PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1PlayAudio {
            get {
                return ((bool)(this["Post1PlayAudio"]));
            }
            set {
                this["Post1PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2PlayAudio {
            get {
                return ((bool)(this["Post2PlayAudio"]));
            }
            set {
                this["Post2PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3PlayAudio {
            get {
                return ((bool)(this["Post3PlayAudio"]));
            }
            set {
                this["Post3PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioSpellNumber {
            get {
                return ((bool)(this["AudioSpellNumber"]));
            }
            set {
                this["AudioSpellNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLogo {
            get {
                return ((bool)(this["ShowLogo"]));
            }
            set {
                this["ShowLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\DisplayLogoImg.png")]
        public string DisplayLogoImg {
            get {
                return ((string)(this["DisplayLogoImg"]));
            }
            set {
                this["DisplayLogoImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tobasa Queue System")]
        public string DisplayLogoText {
            get {
                return ((string)(this["DisplayLogoText"]));
            }
            set {
                this["DisplayLogoText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInfoTextTop {
            get {
                return ((bool)(this["ShowInfoTextTop"]));
            }
            set {
                this["ShowInfoTextTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BasicQueueMode {
            get {
                return ((bool)(this["BasicQueueMode"]));
            }
            set {
                this["BasicQueueMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4BC3A3AC2D6D367A74580388B20BC069C96B048DFEAF5CCDC0CE1E25BF23F39")]
        public string SecuritySalt {
            get {
                return ((string)(this["SecuritySalt"]));
            }
            set {
                this["SecuritySalt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOMER SERVICE")]
        public string Post4Caption {
            get {
                return ((string)(this["Post4Caption"]));
            }
            set {
                this["Post4Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST4")]
        public string Post4Post {
            get {
                return ((string)(this["Post4Post"]));
            }
            set {
                this["Post4Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4Name {
            get {
                return ((string)(this["Post4Name"]));
            }
            set {
                this["Post4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4RunText {
            get {
                return ((string)(this["Post4RunText"]));
            }
            set {
                this["Post4RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4PlayAudio {
            get {
                return ((bool)(this["Post4PlayAudio"]));
            }
            set {
                this["Post4PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4Visible {
            get {
                return ((bool)(this["Post4Visible"]));
            }
            set {
                this["Post4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlaySimpleSoundNotification {
            get {
                return ((bool)(this["PlaySimpleSoundNotification"]));
            }
            set {
                this["PlaySimpleSoundNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateNumberFromOtherPost {
            get {
                return ((bool)(this["UpdateNumberFromOtherPost"]));
            }
            set {
                this["UpdateNumberFromOtherPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMessageTextMiddle {
            get {
                return ((bool)(this["ShowMessageTextMiddle"]));
            }
            set {
                this["ShowMessageTextMiddle"] = value;
            }
        }
    }
}
