//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tobasa.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tobasa Queue Display")]
        public string AppName {
            get {
                return ((string)(this["AppName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public string AppVersion {
            get {
                return ((string)(this["AppVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VideoClip")]
        public string VideoSource {
            get {
                return ((string)(this["VideoSource"]));
            }
            set {
                this["VideoSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDevice {
            get {
                return ((string)(this["VideoInputDevice"]));
            }
            set {
                this["VideoInputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SVideo")]
        public string VideoInputDeviceSource {
            get {
                return ((string)(this["VideoInputDeviceSource"]));
            }
            set {
                this["VideoInputDeviceSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlayFromFolder")]
        public string VideoCLipMode {
            get {
                return ((string)(this["VideoCLipMode"]));
            }
            set {
                this["VideoCLipMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartDisplayFullScreen {
            get {
                return ((bool)(this["StartDisplayFullScreen"]));
            }
            set {
                this["StartDisplayFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDevicePath {
            get {
                return ((string)(this["VideoInputDevicePath"]));
            }
            set {
                this["VideoInputDevicePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoInputDeviceName {
            get {
                return ((string)(this["VideoInputDeviceName"]));
            }
            set {
                this["VideoInputDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QueueServerHost {
            get {
                return ((string)(this["QueueServerHost"]));
            }
            set {
                this["QueueServerHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2345")]
        public int QueueServerPort {
            get {
                return ((int)(this["QueueServerPort"]));
            }
            set {
                this["QueueServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DISP#1")]
        public string StationName {
            get {
                return ((string)(this["StationName"]));
            }
            set {
                this["StationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string StationPost {
            get {
                return ((string)(this["StationPost"]));
            }
            set {
                this["StationPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\wav")]
        public string NumberAudioLocation {
            get {
                return ((string)(this["NumberAudioLocation"]));
            }
            set {
                this["NumberAudioLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string MaxQueueNumber {
            get {
                return ((string)(this["MaxQueueNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string MaxStationNumber {
            get {
                return ((string)(this["MaxStationNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int QueueAnimationTimeInSecond {
            get {
                return ((int)(this["QueueAnimationTimeInSecond"]));
            }
            set {
                this["QueueAnimationTimeInSecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("APOTIK")]
        public string Post0Caption {
            get {
                return ((string)(this["Post0Caption"]));
            }
            set {
                this["Post0Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST0")]
        public string Post0Post {
            get {
                return ((string)(this["Post0Post"]));
            }
            set {
                this["Post0Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0Name {
            get {
                return ((string)(this["Post0Name"]));
            }
            set {
                this["Post0Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LABORATORIUM")]
        public string Post1Caption {
            get {
                return ((string)(this["Post1Caption"]));
            }
            set {
                this["Post1Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST1")]
        public string Post1Post {
            get {
                return ((string)(this["Post1Post"]));
            }
            set {
                this["Post1Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1Name {
            get {
                return ((string)(this["Post1Name"]));
            }
            set {
                this["Post1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PENDAFTARAN RJ")]
        public string Post2Caption {
            get {
                return ((string)(this["Post2Caption"]));
            }
            set {
                this["Post2Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST2")]
        public string Post2Post {
            get {
                return ((string)(this["Post2Post"]));
            }
            set {
                this["Post2Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran")]
        public string Post2Name {
            get {
                return ((string)(this["Post2Name"]));
            }
            set {
                this["Post2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS KESEHATAN")]
        public string Post3Caption {
            get {
                return ((string)(this["Post3Caption"]));
            }
            set {
                this["Post3Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST3")]
        public string Post3Post {
            get {
                return ((string)(this["Post3Post"]));
            }
            set {
                this["Post3Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS Kesehatan")]
        public string Post3Name {
            get {
                return ((string)(this["Post3Name"]));
            }
            set {
                this["Post3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apotik")]
        public string Post0RunText {
            get {
                return ((string)(this["Post0RunText"]));
            }
            set {
                this["Post0RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laboratorium")]
        public string Post1RunText {
            get {
                return ((string)(this["Post1RunText"]));
            }
            set {
                this["Post1RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pendaftaran")]
        public string Post2RunText {
            get {
                return ((string)(this["Post2RunText"]));
            }
            set {
                this["Post2RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPJS")]
        public string Post3RunText {
            get {
                return ((string)(this["Post3RunText"]));
            }
            set {
                this["Post3RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color NumberAnimationColor {
            get {
                return ((global::System.Drawing.Color)(this["NumberAnimationColor"]));
            }
            set {
                this["NumberAnimationColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3Visible {
            get {
                return ((bool)(this["Post3Visible"]));
            }
            set {
                this["Post3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DSEngineVolumeLevel {
            get {
                return ((int)(this["DSEngineVolumeLevel"]));
            }
            set {
                this["DSEngineVolumeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartNumberWithUnderscore {
            get {
                return ((bool)(this["StartNumberWithUnderscore"]));
            }
            set {
                this["StartNumberWithUnderscore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\movie")]
        public string VideoClipLocation {
            get {
                return ((string)(this["VideoClipLocation"]));
            }
            set {
                this["VideoClipLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayVideoAtStartup {
            get {
                return ((bool)(this["PlayVideoAtStartup"]));
            }
            set {
                this["PlayVideoAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReceiveMessageFromOtherPost {
            get {
                return ((bool)(this["ReceiveMessageFromOtherPost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tobasaqueue")]
        public string QueueUserName {
            get {
                return ((string)(this["QueueUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e4ee0e54215f5e3dd7683923abe1dac8")]
        public string QueuePassword {
            get {
                return ((string)(this["QueuePassword"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Selamat Datang")]
        public string RunningText0 {
            get {
                return ((string)(this["RunningText0"]));
            }
            set {
                this["RunningText0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terimakasih")]
        public string RunningText1 {
            get {
                return ((string)(this["RunningText1"]));
            }
            set {
                this["RunningText1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0PlayAudio {
            get {
                return ((bool)(this["Post0PlayAudio"]));
            }
            set {
                this["Post0PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1PlayAudio {
            get {
                return ((bool)(this["Post1PlayAudio"]));
            }
            set {
                this["Post1PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2PlayAudio {
            get {
                return ((bool)(this["Post2PlayAudio"]));
            }
            set {
                this["Post2PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post3PlayAudio {
            get {
                return ((bool)(this["Post3PlayAudio"]));
            }
            set {
                this["Post3PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioSpellNumber {
            get {
                return ((bool)(this["AudioSpellNumber"]));
            }
            set {
                this["AudioSpellNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLogo {
            get {
                return ((bool)(this["ShowLogo"]));
            }
            set {
                this["ShowLogo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\DisplayLogoImg.png")]
        public string DisplayLogoImg {
            get {
                return ((string)(this["DisplayLogoImg"]));
            }
            set {
                this["DisplayLogoImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tobasa Queue System")]
        public string DisplayLogoText {
            get {
                return ((string)(this["DisplayLogoText"]));
            }
            set {
                this["DisplayLogoText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C4BC3A3AC2D6D367A74580388B20BC069C96B048DFEAF5CCDC0CE1E25BF23F39")]
        public string SecuritySalt {
            get {
                return ((string)(this["SecuritySalt"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CUSTOMER SERVICE")]
        public string Post4Caption {
            get {
                return ((string)(this["Post4Caption"]));
            }
            set {
                this["Post4Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST4")]
        public string Post4Post {
            get {
                return ((string)(this["Post4Post"]));
            }
            set {
                this["Post4Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4Name {
            get {
                return ((string)(this["Post4Name"]));
            }
            set {
                this["Post4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Customer Service")]
        public string Post4RunText {
            get {
                return ((string)(this["Post4RunText"]));
            }
            set {
                this["Post4RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4PlayAudio {
            get {
                return ((bool)(this["Post4PlayAudio"]));
            }
            set {
                this["Post4PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post4Visible {
            get {
                return ((bool)(this["Post4Visible"]));
            }
            set {
                this["Post4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlaySimpleSoundNotification {
            get {
                return ((bool)(this["PlaySimpleSoundNotification"]));
            }
            set {
                this["PlaySimpleSoundNotification"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateNumberFromOtherPost {
            get {
                return ((bool)(this["UpdateNumberFromOtherPost"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInfoTextTop0 {
            get {
                return ((bool)(this["ShowInfoTextTop0"]));
            }
            set {
                this["ShowInfoTextTop0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInfoTextTop1 {
            get {
                return ((bool)(this["ShowInfoTextTop1"]));
            }
            set {
                this["ShowInfoTextTop1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioUseLoket {
            get {
                return ((bool)(this["AudioUseLoket"]));
            }
            set {
                this["AudioUseLoket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioLoketIDUseAlphabet {
            get {
                return ((bool)(this["AudioLoketIDUseAlphabet"]));
            }
            set {
                this["AudioLoketIDUseAlphabet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFinishedQueue {
            get {
                return ((bool)(this["ShowFinishedQueue"]));
            }
            set {
                this["ShowFinishedQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI GIGI")]
        public string Post5Caption {
            get {
                return ((string)(this["Post5Caption"]));
            }
            set {
                this["Post5Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST5")]
        public string Post5Post {
            get {
                return ((string)(this["Post5Post"]));
            }
            set {
                this["Post5Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Gigi")]
        public string Post5Name {
            get {
                return ((string)(this["Post5Name"]));
            }
            set {
                this["Post5Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Gigi")]
        public string Post5RunText {
            get {
                return ((string)(this["Post5RunText"]));
            }
            set {
                this["Post5RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post5PlayAudio {
            get {
                return ((bool)(this["Post5PlayAudio"]));
            }
            set {
                this["Post5PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post5Visible {
            get {
                return ((bool)(this["Post5Visible"]));
            }
            set {
                this["Post5Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI ANAK")]
        public string Post6Caption {
            get {
                return ((string)(this["Post6Caption"]));
            }
            set {
                this["Post6Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST6")]
        public string Post6Post {
            get {
                return ((string)(this["Post6Post"]));
            }
            set {
                this["Post6Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Anak")]
        public string Post6Name {
            get {
                return ((string)(this["Post6Name"]));
            }
            set {
                this["Post6Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Anak")]
        public string Post6RunText {
            get {
                return ((string)(this["Post6RunText"]));
            }
            set {
                this["Post6RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post6PlayAudio {
            get {
                return ((bool)(this["Post6PlayAudio"]));
            }
            set {
                this["Post6PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post6Visible {
            get {
                return ((bool)(this["Post6Visible"]));
            }
            set {
                this["Post6Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI MATA")]
        public string Post7Caption {
            get {
                return ((string)(this["Post7Caption"]));
            }
            set {
                this["Post7Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST7")]
        public string Post7Post {
            get {
                return ((string)(this["Post7Post"]));
            }
            set {
                this["Post7Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Mata")]
        public string Post7Name {
            get {
                return ((string)(this["Post7Name"]));
            }
            set {
                this["Post7Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Mata")]
        public string Post7RunText {
            get {
                return ((string)(this["Post7RunText"]));
            }
            set {
                this["Post7RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post7PlayAudio {
            get {
                return ((bool)(this["Post7PlayAudio"]));
            }
            set {
                this["Post7PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post7Visible {
            get {
                return ((bool)(this["Post7Visible"]));
            }
            set {
                this["Post7Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI KULIT")]
        public string Post8Caption {
            get {
                return ((string)(this["Post8Caption"]));
            }
            set {
                this["Post8Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST8")]
        public string Post8Post {
            get {
                return ((string)(this["Post8Post"]));
            }
            set {
                this["Post8Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Kulit")]
        public string Post8Name {
            get {
                return ((string)(this["Post8Name"]));
            }
            set {
                this["Post8Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli Kulit")]
        public string Post8RunText {
            get {
                return ((string)(this["Post8RunText"]));
            }
            set {
                this["Post8RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post8PlayAudio {
            get {
                return ((bool)(this["Post8PlayAudio"]));
            }
            set {
                this["Post8PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post8Visible {
            get {
                return ((bool)(this["Post8Visible"]));
            }
            set {
                this["Post8Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POLI THT")]
        public string Post9Caption {
            get {
                return ((string)(this["Post9Caption"]));
            }
            set {
                this["Post9Caption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("POST9")]
        public string Post9Post {
            get {
                return ((string)(this["Post9Post"]));
            }
            set {
                this["Post9Post"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli THT")]
        public string Post9Name {
            get {
                return ((string)(this["Post9Name"]));
            }
            set {
                this["Post9Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poli THT")]
        public string Post9RunText {
            get {
                return ((string)(this["Post9RunText"]));
            }
            set {
                this["Post9RunText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post9PlayAudio {
            get {
                return ((bool)(this["Post9PlayAudio"]));
            }
            set {
                this["Post9PlayAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post9Visible {
            get {
                return ((bool)(this["Post9Visible"]));
            }
            set {
                this["Post9Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post0Visible {
            get {
                return ((bool)(this["Post0Visible"]));
            }
            set {
                this["Post0Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post1Visible {
            get {
                return ((bool)(this["Post1Visible"]));
            }
            set {
                this["Post1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Post2Visible {
            get {
                return ((bool)(this["Post2Visible"]));
            }
            set {
                this["Post2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainPostCounterText {
            get {
                return ((string)(this["MainPostCounterText"]));
            }
            set {
                this["MainPostCounterText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowRightPosts {
            get {
                return ((bool)(this["ShowRightPosts"]));
            }
            set {
                this["ShowRightPosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowLeftPosts {
            get {
                return ((bool)(this["ShowLeftPosts"]));
            }
            set {
                this["ShowLeftPosts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCenterMiddleDiv {
            get {
                return ((bool)(this["ShowCenterMiddleDiv"]));
            }
            set {
                this["ShowCenterMiddleDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SwapCounterNumberLabelPosition {
            get {
                return ((bool)(this["SwapCounterNumberLabelPosition"]));
            }
            set {
                this["SwapCounterNumberLabelPosition"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>POST0</string>
  <string>POST1</string>
  <string>POST2</string>
  <string>POST3</string>
  <string>POST4</string>
  <string>POST5</string>
  <string>POST6</string>
  <string>POST7</string>
  <string>POST8</string>
  <string>POST9</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UIPostList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UIPostList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\img\\DisplayMainBrandingImage.png")]
        public string DisplayMainBrandingImage {
            get {
                return ((string)(this["DisplayMainBrandingImage"]));
            }
            set {
                this["DisplayMainBrandingImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMainBrandingImage {
            get {
                return ((bool)(this["UseMainBrandingImage"]));
            }
            set {
                this["UseMainBrandingImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInfoDialog {
            get {
                return ((bool)(this["ShowInfoDialog"]));
            }
            set {
                this["ShowInfoDialog"] = value;
            }
        }
    }
}
